### ISSUE TITLE
你好,请问下这个怎么设置最大时间和最小时间呢

### ISSUE THREAD

**Issue by Mase9527** [DanielHusx/TimeAxis#1]

**Comment by Mase9527** [comment]
能设置一个时间的范围的吗

**Comment by DanielHusx** [comment]
就2.0.1这个版本来说，要实现的话得在 DHTimeAxis.m的`-updateCurrentTimeIntervalFrom: offset:viewSize:`方法下内先判定下计算的当前时间戳是否超出区间

**Comment by Mase9527** [comment]
> 就2.0.1这个版本来说，要实现的话得在 DHTimeAxis.m的`-updateCurrentTimeIntervalFrom: offset:viewSize:`方法下内先判定下计算的当前时间戳是否超出区间

那如果要调到指定的时间呢,应该要怎么设置呢? 谢谢解答

**Comment by DanielHusx** [comment]
> > 就2.0.1这个版本来说，要实现的话得在 DHTimeAxis.m的`-updateCurrentTimeIntervalFrom: offset:viewSize:`方法下内先判定下计算的当前时间戳是否超出区间
> 
> 那如果要调到指定的时间呢,应该要怎么设置呢? 谢谢解答

完整的源码就在这里，而且相信我的注释已经很明确，这种问题不予回答，抱歉
