### ISSUE TITLE
您好，请问可以修改时间轴的高度吗

### ISSUE THREAD

**Issue by ieliwb** [DanielHusx/TimeAxis#2]
RT，改了高度，下面刻度都不见了，被盖住了

**Comment by DanielHusx** [comment]
> RT，改了高度，下面刻度都不见了，被盖住了

我想知道你咋改的

**Comment by ieliwb** [comment]
大佬好，

- (void)viewDidLoad {
    [super viewDidLoad];

    CGSize viewSize = CGSizeMake(self.view.frame.size.width, 50);
    
    [DHTimeAxisAppearance renderRuleAppearanceWithDirection:DHAxisDirectionHorizontal];
    _axis = [[DHTimeAxis alloc] initWithFrame:CGRectMake(0, self.view.frame.size.height/2.0-50, viewSize.width, viewSize.height)];
    _axis.delegate = self;
    [self.view addSubview:_axis];
    
    _timeLabel = [[UILabel alloc] initWithFrame:CGRectMake(0, CGRectGetMinY(_axis.frame)-40, self.view.frame.size.width, 30)];
    _timeLabel.textAlignment = NSTextAlignmentCenter;
    
    [self.view addSubview:self.timeLabel];
}

就是把 demo里面的100改成50

**Comment by ieliwb** [comment]
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-22 at 18 44 22](https://user-images.githubusercontent.com/2177409/175010657-acee163e-258a-42eb-9509-3e379d87a8cf.png)

刻度都不见了

**Comment by DanielHusx** [comment]
> 不见了



> 大佬好，
> 
> * (void)viewDidLoad {
>   [super viewDidLoad];
>   CGSize viewSize = CGSizeMake(self.view.frame.size.width, 50);
>   [DHTimeAxisAppearance renderRuleAppearanceWithDirection:DHAxisDirectionHorizontal];
>   _axis = [[DHTimeAxis alloc] initWithFrame:CGRectMake(0, self.view.frame.size.height/2.0-50, viewSize.width, viewSize.height)];
>   _axis.delegate = self;
>   [self.view addSubview:_axis];
>   _timeLabel = [[UILabel alloc] initWithFrame:CGRectMake(0, CGRectGetMinY(_axis.frame)-40, self.view.frame.size.width, 30)];
>   _timeLabel.textAlignment = NSTextAlignmentCenter;
>   [self.view addSubview:self.timeLabel];
>   }
> 
> 就是把 demo里面的100改成50

我不是大佬~ 这玩意儿好几年前写的，其实写的挺差的~ 你瞅着乐呵乐呵就行
它不是不见了，因为没有自适应，固定是绘制到距离顶部80的地方去了，你把 DHTimeAxisAppearance+Renderer.m里的第30行 改成 appearance.baseLineFixedOffset = 30.0; 就行了

**Comment by ieliwb** [comment]
谢谢，我下了很多这种，你这个最丝滑
